services:
  fba_ui:
    image: nginx:latest
    ports:
      - '5173:80'
    container_name: fba_ui
    restart: always
    volumes:
      - ./scripts/deploy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./apps/web-antdv-next/dist:/var/www/fba_ui:ro
    extra_hosts:
      - 'host.docker.internal:host-gateway'
