networks:
  fba_network:
    # name: fba_network
    # driver: bridge
    external: true

volumes:
  fba_static:
    external: true
  fba_static_upload:
    external: true

services:
  fba_ui:
    build:
      context: .
      dockerfile: Dockerfile
    image: fba_ui:latest
    ports:
      - '80:80'
    container_name: fba_ui
    restart: always
    command:
      - nginx
      - -g
      - daemon off;
    volumes:
      - fba_static:/var/www/fba_server/backend/static
      - fba_static_upload:/var/www/fba_server/backend/static/upload
    networks:
      - fba_network
